# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  
steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'  
    dotnet test StatlerWaldorfCorp.TeamService.Tests --configuration $(buildConfiguration) --logger trx
    dotnet test StatlerWaldorfCorp.TeamService.Tests.Integration --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
